name: birdcam
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - ffmpeg
  - ffmpeg-python
  - numpy
  - pandas
  - pytorch
  - opencv
  - moviepy
  - watchdog
  - google-api-python-client 
  - google-auth
  - google-auth-oauthlib
  - google-auth-httplib2
